alias nt='netstat -lntp'
alias df='df -h'
alias d='docker'
alias dsa='docker ps -a'
alias ds='docker ps'
alias di='docker images'
alias fm='free -m'
alias kube='microk8s.kubectl'
alias hel='microk8s.helm3'
alias dstop="systemctl stop docker.socket"
alias dstart="systemctl start docker.socket"
alias terr='/usr/bin/terraform'
alias dot="dotnet"
alias dpose="/usr/bin/docker-compose"
alias dlg="docker logs"
alias vcs="systemctl start vnc"
alias vcsp="systemctl stop vnc"
